"""empty message

Revision ID: 935c7080f3b0
Revises: 7b90ae616808
Create Date: 2020-09-15 00:33:27.256322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935c7080f3b0'
down_revision = '7b90ae616808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camname', sa.String(length=64), nullable=True),
    sa.Column('end', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cam_camname'), 'cam', ['camname'], unique=True)
    op.create_index(op.f('ix_cam_end'), 'cam', ['end'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cam_end'), table_name='cam')
    op.drop_index(op.f('ix_cam_camname'), table_name='cam')
    op.drop_table('cam')
    # ### end Alembic commands ###
