"""empty message

Revision ID: ac5c71f51ea9
Revises: 935c7080f3b0
Create Date: 2020-09-15 10:50:00.844138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5c71f51ea9'
down_revision = '935c7080f3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cam_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cam_id'], ['cam.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postcam_cam_id'), 'postcam', ['cam_id'], unique=False)
    op.create_index(op.f('ix_postcam_timestamp'), 'postcam', ['timestamp'], unique=False)
    op.create_index(op.f('ix_postcam_vehicle_id'), 'postcam', ['vehicle_id'], unique=False)
    op.create_table('postuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['cam.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postuser_timestamp'), 'postuser', ['timestamp'], unique=False)
    op.create_index(op.f('ix_postuser_user_id'), 'postuser', ['user_id'], unique=False)
    op.create_index(op.f('ix_postuser_vehicle_id'), 'postuser', ['vehicle_id'], unique=False)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_postuser_vehicle_id'), table_name='postuser')
    op.drop_index(op.f('ix_postuser_user_id'), table_name='postuser')
    op.drop_index(op.f('ix_postuser_timestamp'), table_name='postuser')
    op.drop_table('postuser')
    op.drop_index(op.f('ix_postcam_vehicle_id'), table_name='postcam')
    op.drop_index(op.f('ix_postcam_timestamp'), table_name='postcam')
    op.drop_index(op.f('ix_postcam_cam_id'), table_name='postcam')
    op.drop_table('postcam')
    # ### end Alembic commands ###
