"""add cpf to user

Revision ID: d6fd214c58c9
Revises: ac5c71f51ea9
Create Date: 2020-10-04 12:29:34.233235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fd214c58c9'
down_revision = 'ac5c71f51ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cpf', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_user_cpf'), 'user', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cpf'), table_name='user')
    op.drop_column('user', 'cpf')
    # ### end Alembic commands ###
